name = "screenshot-worker"
compatibility_date = "2024-06-03"
node_compat = true
logpush = true
browser = { binding = "MYBROWSER" }

# [vars]
# MY_VAR = "my-variable"

#[[kv_namespaces]]
#binding = "xxx"
#id = "xxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"
